services:
  wpp:
    image: wppconnect/server-cli:main
    container_name: wppconnect
    networks:
      - net
    restart: always
    ports:
      - "8075:21465"
      - "8074:8080"
    volumes:
      - ./config.json:/usr/src/wpp-server/config.json
      - ./create-config.js:/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/config/create-config.js
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S http://localhost:21465/api-docs/ || exit 1"]
      interval: 60s 
      timeout: 10s
      retries: 3
    command: wppserver -c /usr/src/wpp-server/config.json

networks:
  net:
    driver: bridge